name: alazhar
type: 'nodejs:14'
hooks:
  build: |
    npm install
    npm run build
# relationships:
#   database: "strapi-mysql:mysql"
# variables:
#   DATABASE_CLIENT: "mysql"
#   DATABASE_HOST: "strapi-mysql.internal"
#   DATABASE_PORT: "3306"
#   DATABASE_NAME: "your_database_name"
#   DATABASE_USERNAME: "your_mysql_username"
#   DATABASE_PASSWORD: "your_mysql_password"
